### ISSUE TITLE
Missing Repo on bintray

### ISSUE THREAD

**Issue by andreas-barthel** [tronprotocol/trident#1]
On Bintray there is no trident repositry so maven can't download the artifacts

**Comment by deniben** [comment]
![image](https://user-images.githubusercontent.com/19304301/112823201-a8b4a200-9091-11eb-9f39-a37161751851.png)
Really

**Comment by deniben** [comment]
![image](https://user-images.githubusercontent.com/19304301/112823262-bc600880-9091-11eb-87b9-21d78529ade2.png)

**Comment by andreas-barthel** [comment]
@deniben Thanks for the info.
Nice to see that the developers has uploaded it three days **after** i have opened the ticket (**without**  informing us...)
