### ISSUE TITLE
make signed transaction offline

### ISSUE THREAD

**Issue by fereshteh-jvz** [tronprotocol/trident#100]
How to make signed transaction offline? Right now I can make signed transaction with apiWrapper. But in my case I cannot connect to nodes and I need to create and sign the transaction offline so I can broadcast it with https://api.trongrid.io/wallet/broadcasttransaction api. Thanks in advance for your help

**Comment by lxcmyf** [comment]
@fereshteh-jvz 
Please refer to trident sdk, https://github.com/tronprotocol/trident/blob/master/trident-java/core/src/main/java/org/tron/trident/core/ApiWrapper.java
```
public Chain.Transaction signTransaction(Response.TransactionExtention txnExt, KeyPair keyPair) {
        byte[] txid = txnExt.getTxid().toByteArray();
        byte[] signature = KeyPair.signTransaction(txid, keyPair);
        Chain.Transaction signedTxn = txnExt.getTransaction().toBuilder().addSignature(ByteString.copyFrom(signature)).build();
        return signedTxn;
    }
```

**Comment by eodiandie** [comment]
will close this issue, seems this issue has been resolved already.
