### ISSUE TITLE
hello when i try to compile with the latest version i get the following error i dont know what to do please help me thanks

### ISSUE THREAD

**Issue by 1104190950** [tronprotocol/trident#102]
![err](https://github.com/tronprotocol/trident/assets/39689024/ec576122-db10-4a02-92f4-37c107e2bff3)

**Comment by 1104190950** [comment]
A problem occurred configuring project ':core'.
> Could not resolve all artifacts for configuration ':core:classpath'.
   > Could not resolve com.google.guava:guava:27.0.1-jre.
     Required by:
         project :core > com.google.protobuf:com.google.protobuf.gradle.plugin:0.8.12 > gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.12
      > Could not resolve com.google.guava:guava:27.0.1-jre.
         > Could not get resource 'https://plugins.gradle.org/m2/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve com.google.gradle:osdetector-gradle-plugin:1.6.2.
     Required by:
         project :core > com.google.protobuf:com.google.protobuf.gradle.plugin:0.8.12 > gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.12
      > Could not resolve com.google.gradle:osdetector-gradle-plugin:1.6.2.
         > Could not get resource 'https://plugins.gradle.org/m2/com/google/gradle/osdetector-gradle-plugin/1.6.2/osdetector-gradle-plugin-1.6.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/gradle/osdetector-gradle-plugin/1.6.2/osdetector-gradle-plugin-1.6.2.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve commons-lang:commons-lang:2.6.
     Required by:
         project :core > com.google.protobuf:com.google.protobuf.gradle.plugin:0.8.12 > gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.12
      > Could not resolve commons-lang:commons-lang:2.6.
         > Could not get resource 'https://plugins.gradle.org/m2/commons-lang/commons-lang/2.6/commons-lang-2.6.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/commons-lang/commons-lang/2.6/commons-lang-2.6.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by mikeluxue** [comment]
@1104190950 From the errors you describe above, it went wrong when getting/resolving some dependent jars(e.g.: guava.jar) from the gradle repository. It seems like there is something wrong in your local network, could you check your local network to make sure it can visit the gradle/maven repository normally? By the way, if you have a VPN setting, please check to make sure the VPN works well

**Comment by 1104190950** [comment]
Thank you, I'll check the network

**Comment by 1104190950** [comment]
> @1104190950 From the errors you describe above, it went wrong when getting/resolving some dependent jars(e.g.: guava.jar) from the gradle repository. It seems like there is something wrong in your local network, could you check your local network to make sure it can visit the gradle/maven repository normally? By the way, if you have a VPN setting, please check to make sure the VPN works well

Thank you very much, the compilation failure due to network problems has now been resolved
