### ISSUE TITLE
How does the method determine the transaction type of 'approved' or 'transferred'?

### ISSUE THREAD

**Issue by gedowangvs97** [tronprotocol/trident#111]
“getTransactionById” How does the method determine the transaction type of 'approved' or 'transferred'? Or is there any way to tell the difference?
Demo TxId：
232a8da14f777c360ec398568ae828852a60d64507fb482b118c922b1cb8cdbe
42eb88afe779f8e639cc758f688b192f9f2988db69a6f0c87e3282347b3b7635

**Comment by ferdinand026** [comment]
@gedowangvs97 For Tronscan, 'approved' or 'transferred' is only a description of the contract method called in this transaction. For the method specified by TRC standard, Tronscan will translate it to more readable statement with more obvious key information, for example, for [approve transaction](https://tronscan.org/#/transaction/232a8da14f777c360ec398568ae828852a60d64507fb482b118c922b1cb8cdbe).

About how to determine the transaction type of the transaction which get through "getTransactionById" API,  "raw_data.contract[0].type is the transaction type. For the type of triggerSmartContract, the invocation method can be obtained through "raw_data. contract[0]. parameter. value. data" filed, and the first 4 bytes is the method, we need to decode the data, please refer to the [guide](https://developers.tron.network/docs/parameter-encoding-and-decoding#parameter-decoding).

**Comment by Aiden-777** [comment]
``` java
public static final String APPROVE_FUNC_ID_BY_KECCAK256 =
        Hex.toHexString(
                new Keccak.Digest256().digest("approve(address, uint256)".getBytes())
        ).substring(0, 8);
```

``` java
String data = Hex.toHexString(triggerSmartContract.getData().toByteArray());

if (!TronConstants.APPROVE_FUNC_ID_BY_KECCAK256 .equals(funcId)) {
    ...
}

```

**Comment by gedowangvs97** [comment]
How to get this **fundId** field？

if (!TronConstants.APPROVE_FUNC_ID_BY_KECCAK256 .equals(funcId)) {
    ...
}

**Comment by Aiden-777** [comment]
https://developers.tron.network/docs/parameter-encoding-and-decoding

```  java

String funcId = data.substring(0, 8);

```

**Comment by gedowangvs97** [comment]
approve TxId：
232a8da14f777c360ec398568ae828852a60d64507fb482b118c922b1cb8cdbe

String funcId = data.substring(0, 8); 
// substring：095ea7b3

public static final String APPROVE_FUNC_ID_BY_KECCAK256 =
        Hex.toHexString(
                new Keccak.Digest256().digest("approve(address, uint256)".getBytes())
        ).substring(0, 8);
// 8b069f2a

Why are the above two values different?

**Comment by ferdinand026** [comment]
> approve TxId： 232a8da14f777c360ec398568ae828852a60d64507fb482b118c922b1cb8cdbe
> 
> String funcId = data.substring(0, 8); // substring：095ea7b3
> 
> public static final String APPROVE_FUNC_ID_BY_KECCAK256 = Hex.toHexString( new Keccak.Digest256().digest("approve(address, uint256)".getBytes()) ).substring(0, 8); // 8b069f2a
> 
> Why are the above two values different?

There should be no any space in the function method. Remove all the spaces and it will be "approve(address,uint256)"

**Comment by Aiden-777** [comment]
> > approve TxId： 232a8da14f777c360ec398568ae828852a60d64507fb482b118c922b1cb8cdbe
> > String funcId = data.substring(0, 8); // substring：095ea7b3
> > public static final String APPROVE_FUNC_ID_BY_KECCAK256 = Hex.toHexString( new Keccak.Digest256().digest("approve(address, uint256)".getBytes()) ).substring(0, 8); // 8b069f2a
> > Why are the above two values different?
> 
> There should be no any space in the function method. Remove all the spaces and it will be "approve(address,uint256)"

Yes, I made a stupid mistake and have corrected it.

**Comment by eodiandie** [comment]
will close it ,cus it is fixed;
