### ISSUE TITLE
Can't I know the contents of the data of TriggerSmartContract?

### ISSUE THREAD

**Issue by wowjavakr** [tronprotocol/trident#116]
Hello,

Can't I know the contents of the data of TriggerSmartContract?
I'd like to check the history of Token Transfer.

How can I get the data of red box?
![a](https://github.com/tronprotocol/trident/assets/57401324/bcfea329-4299-4a4b-a7a3-45b2a3cbc963)

https://tronscan.org/#/transaction/079adf4f3c3a85d169a770d2103662a0c98e18628630de613ec4ea46205644d0

Thanks.

**Comment by lxcmyf** [comment]
@wowjavakr 
For details, please refer to: https://developers.tron.network/reference/get-account-info-by-address

**Comment by eodiandie** [comment]
will close this issue as for no more relpy in a long time;
