### ISSUE TITLE
如何Function构建二维数组？

### ISSUE THREAD

**Issue by qfengthree** [tronprotocol/trident#117]
使用trident-java中

1. Function1: methodName(address[] path) returns (uint256)
可以用这样构建：
        DynamicArray<Address> dynamicArrayPath = new DynamicArray<Address>(Address.class, pathList);
2.  methodName2(address[][] path) returns (uint256) 
请教一下methodName2，如何构建二维数组？

**Comment by endiaoekoe** [comment]
hi @qfengthree 
you can try this, as below:

       ```
        // Construct a two-dimensional array of addresses
        Address[][] twoDimensionalPath = new Address[][] {
            {new Address("0x123"), new Address("0x456")},
            {new Address("0x789"), new Address("0xabc")}
        };

        // Building two-dimensional arrays with DynamicArray
        DynamicArray dynamicArrayPath = new DynamicArray(Address.class, twoDimensionalPath);

        // invoke methodName2 method
        uint256 result = methodName2(dynamicArrayPath);
```

**Comment by endiaoekoe** [comment]
> 1. DynamicArray
@qfengthree 
I just checked the source code of DynamicArray.java, only public constructors can be used,
```
  public DynamicArray(Class<T> type, List<T> values) {
        super(type, values);
    }
```
guess you want to construct a Function object, like this
  ```
  final Function function =
                new Function(
                        "addParticipants",
                        Arrays.asList(
                                new DynamicArray<>(
                                        Bytes32.class, Utils.typeMap(participants, Bytes32.class))),
                        Collections.emptyList());
```
if you insist on using two-d arrays, I suggest you transform the 2-D arrays to a 2-D List Object, then pass to the constructor function.
which may be like this,
```
    int[][] twoDimensionalArray = {
            {1, 2, 3},
            {4, 5, 6},
            {7, 8, 9}
        };
        List<List<Integer>> twoDimensionalList = Arrays.stream(twoDimensionalArray)
                .map(row -> Arrays.stream(row).boxed().collect(Collectors.toList()))
                .collect(Collectors.toList());

```
hope it helps.

**Comment by endiaoekoe** [comment]
> AbiTypes

that's right. currently, it can not use 2-D array as parameters when constructing function. you can only pass limited types， eg: Uint256, Address, and BigInteger.

**Comment by endiaoekoe** [comment]
@qfengthree 

line ’Utils.typeMap(paths, DynamicArray.class, Address.class)‘ which should return a list contains two DynamicArray object.
<img width="399" alt="image" src="https://github.com/tronprotocol/trident/assets/7970865/7abf76c7-aedb-4efb-9a5f-a504c90d7b84">

so

 `   DynamicArray _versionLens = new DynamicArray<>(Uint256.class, Utils.typeMap(versionLens, DynamicArray.class, Uint256.class));`
should be 
`        DynamicArray _versionLens = new DynamicArray<>(DynamicArray.class, Utils.typeMap(versionLens, DynamicArray.class, Uint256.class));`
same for other lines.

but I just debug your code in my local machine,when encode the DynamicArray(which contains a list have 2 DynamicArray object),form a nested loops。and the output is wrong and be different from your result running with js.

**Comment by eodiandie** [comment]
will close this issue ,cus author has already find the solutions
