### ISSUE TITLE
How to parse json content

### ISSUE THREAD

**Issue by YaakovHuang** [tronprotocol/trident#12]
I am interacting with the dapp and got the json content returned by the dapp, I want to parse json content into Transaction then broadcast the transaction after signing, how should I deal with this problem? 

![WX20210513-152306](https://user-images.githubusercontent.com/9527803/118092820-30b2f900-b3ff-11eb-9b0d-b4282d3a9e4a.png)

**Comment by Starsakary** [comment]
You can find many JSON libraries from Google to solve this.

**Comment by YaakovHuang** [comment]
> You can find many JSON libraries from Google to solve this.
I want to know is there any way to construct this transaction?

**Comment by YaakovHuang** [comment]
@Starsakary 
 I want to know is there any way to construct this transaction? thanks.

**Comment by Starsakary** [comment]
I suggest you read the "Smart Contract" part of the documentation.

**Comment by YaakovHuang** [comment]
I read this part, but found no useful information. What I need to do now is to deserialize the json formatted transaction returned from the web into a Transaction, but I just didn't find a way to construct this Transaction.

**Comment by yangkun0824** [comment]
also i don't know how to parse the parameter.value bytestring?

**Comment by yangkun0824** [comment]
@Starsakary

**Comment by yangkun0824** [comment]
in the trident, i can only get the value part in bytestring format. how can i parse the contract_address, owner_address part?

transaction.getRawDataOrBuilder().getContract(0).getParameterOrBuilder().getValue()

**Comment by Starsakary** [comment]
I'm giving an example of building a transaction of `TriggerSmartContract`:
```java
public String transfer(String destAddr, long amount, 
             String memo, long feeLimit) throws Exception {
        Function transfer = new Function("transfer",
                Arrays.asList(new Address(destAddr),
                        new Uint256(BigInteger.valueOf(amount).multiply(BigInteger.valueOf(10).pow(decimal)))),
                Arrays.asList(new TypeReference<Bool>() {}));

        TransactionBuilder builder = client.triggerCall(Base58Check.bytesToBase58(ownerAddr.toByteArray()), 
                Base58Check.bytesToBase58(cntrAddr.toByteArray()), transfer);
        builder.setFeeLimit(feeLimit);
        builder.setMemo(memo);

        Transaction signedTxn = client.signTransaction(builder.build());
        return client.broadcastTransaction(signedTxn);
      }
```

**Comment by Starsakary** [comment]
This is closed due to being not active.
