### ISSUE TITLE
The "activated" field of an Account

### ISSUE THREAD

**Issue by gedowangvs97** [tronprotocol/trident#128]
I need to query the activation status of an Account. Where can I obtain it from?

Response.Account account = wrapper.getAccount(findAddress);
//This field cannot be queried

**Comment by endiaoekoe** [comment]
> I need to query the activation status of an Account. Where can I obtain it from?
> 
> Response.Account account = wrapper.getAccount(findAddress); //This field cannot be queried

hi, @gedowangvs97 
Through [tron's definition about ’Account activated‘](https://developers.tron.network/docs/account#account-activation),Accounts can be activated in the following two ways:

- Send any amount of TRX or TRC-10 tokens from an existing account to the new account;
- Call Java-tron's wallet/createaccountAPI to create a transaction from an existing account, then sign the transaction and broadcast it to the TRON network.

So in Tron network, if you can query an account through 'getAccount' interface and the result it returns is not empty,which means this account has been/is activated;
