### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by przhevvalsky** [tronprotocol/trident#129]
Hi, I need to send a transaction to TRX test network - Shasta. On this site - https://developers.tron.network/reference/sending-transactions, there is an example how to do it using Tridient SDK. - 
![image](https://github.com/tronprotocol/trident/assets/159006477/c39917b2-28dc-45de-bb7d-30e58a1b907c)

After successfully adding the jar files to my project, I proceeded with further implementation based on the information provided in the link above. I implemented the transfer method as described in the example, but initially I didn't have access to the createTransaction2 method call, so I had to uncomment it in api.proto and rebuild and add the exposed jar files to my project. ![image](https://github.com/tronprotocol/trident/assets/159006477/8839d2f3-bae7-4002-9532-c7287e2db970) 

After that, when I run the transfer method, an error is thrown. ![image](https://github.com/tronprotocol/trident/assets/159006477/5e4e95d3-3ea3-4e34-bdf1-4a54c3d5794d)

Using debug, the exact place in this method 
![image](https://github.com/tronprotocol/trident/assets/159006477/a36ca9b2-77d8-4f0f-b7bd-c88cbe055985) 
![image](https://github.com/tronprotocol/trident/assets/159006477/17d81830-36f1-4534-bbc6-d2b270d78bd6)
![image](https://github.com/tronprotocol/trident/assets/159006477/3e32050a-2386-484f-b555-92bfecdc61f7)

Could you help me to solve that problem, please

**Comment by endiaoekoe** [comment]
hi, @przhevvalsky 
currently, only createTransaction() method is supported via grpc endpoint accessing. check it out [here](https://developers.tron.network/reference/createtransaction)
From the error you described above. which means it is not supported on the server side.
if you want to test transfer assets, you can use the transfer() method directly.

**Comment by angrynurd** [comment]
@przhevvalsky will close this issue, if you have any questions please reopen it,thanks;
