### ISSUE TITLE
how to decode the parameter.value part byte string?

### ISSUE THREAD

**Issue by yangkun0824** [tronprotocol/trident#13]
In trident java, I can only get the contract parameter value part of the getTransactionId call. I can't get the value.data part for smart contract or value.amount part for transfer contract. 

I want ask how to decode the value byte string to get the data part and amount part.

the following value part in byte string is 0a154162e8c7348c19743c4b949aa874d61b2bbbdab189121541a614f803b6fd780986a42c78ec9c7f77e6ded13c2244a9059cbb00000000000000000000000021324d0095754135f5994eecea53547ab698dd7400000000000000000000000000000000000000000000000000000000072b0723

"contract": [{
			"parameter": {
				"value": {
					"data": "a9059cbb00000000000000000000000021324d0095754135f5994eecea53547ab698dd7400000000000000000000000000000000000000000000000000000000072b0723",
					"owner_address": "4162e8c7348c19743c4b949aa874d61b2bbbdab189",
					"contract_address": "41a614f803b6fd780986a42c78ec9c7f77e6ded13c"
				},
				"type_url": "type.googleapis.com/protocol.TriggerSmartContract"
			},
			"type": "TriggerSmartContract"
}],

**Comment by yangkun0824** [comment]
the following value part in byte string is 0a154130760c7e10b1d3509d8d64a7e9eb9ab94bc83495121541166db04f0a9745521c9c6e1f1f55045a78affca11880dac409, I can get the owner_address, to_address, but don't know how to get the amount part.


"contract": [{
			"parameter": {
				"value": {
					"amount": 20000000,
					"owner_address": "4130760c7e10b1d3509d8d64a7e9eb9ab94bc83495",
					"to_address": "41166db04f0a9745521c9c6e1f1f55045a78affca1"
				},
				"type_url": "type.googleapis.com/protocol.TransferContract"
			},
			"type": "TransferContract"
		}],

**Comment by Starsakary** [comment]
My colleague and I have answered such questions, https://github.com/tronprotocol/trident/issues/8
You'd better learn the encoding rules of Protobuf and smart contract ABI to permanently solve such problems.

**Comment by yangkun0824** [comment]
thanks
