### ISSUE TITLE
add break; for each switch case

### ISSUE THREAD

**Issue by godmonth** [tronprotocol/trident#133]
https://github.com/tronprotocol/trident/blob/main/trident-java/core/src/main/java/org/tron/trident/core/ApiWrapper.java

**add break; for each case**

    private String resolveResultCode(int code) {
        String responseCode = "";
        switch (code) {
            case 0:
                responseCode = "SUCCESS";
                break;
            case 1:
                responseCode = "SIGERROR";
                break;
            case 2:
                responseCode = "CONTRACT_VALIDATE_ERROR";
                break;
            case 3:
                responseCode = "CONTRACT_EXE_ERROR";
                break;
            case 4:
                responseCode = "BANDWITH_ERROR";
                break;
            case 5:
                responseCode = "DUP_TRANSACTION_ERROR";
                break;
            case 6:
                responseCode = "TAPOS_ERROR";
                break;
            case 7:
                responseCode = "TOO_BIG_TRANSACTION_ERROR";
                break;
            case 8:
                responseCode = "TRANSACTION_EXPIRATION_ERROR";
                break;
            case 9:
                responseCode = "SERVER_BUSY";
                break;
            case 10:
                responseCode = "NO_CONNECTION";
                break;
            case 11:
                responseCode = "NOT_ENOUGH_EFFECTIVE_CONNECTION";
                break;
            case 20:
                responseCode = "OTHER_ERROR";
                break;
        }
        return responseCode;
    }

**Comment by endiaoekoe** [comment]
> https://github.com/tronprotocol/trident/blob/main/trident-java/core/src/main/java/org/tron/trident/core/ApiWrapper.java
> 
> **add break; for each case**
> 
> ```
> private String resolveResultCode(int code) {
>     String responseCode = "";
>     switch (code) {
>         case 0:
>             responseCode = "SUCCESS";
>             break;
>         case 1:
>             responseCode = "SIGERROR";
>             break;
>         case 2:
>             responseCode = "CONTRACT_VALIDATE_ERROR";
>             break;
>         case 3:
>             responseCode = "CONTRACT_EXE_ERROR";
>             break;
>         case 4:
>             responseCode = "BANDWITH_ERROR";
>             break;
>         case 5:
>             responseCode = "DUP_TRANSACTION_ERROR";
>             break;
>         case 6:
>             responseCode = "TAPOS_ERROR";
>             break;
>         case 7:
>             responseCode = "TOO_BIG_TRANSACTION_ERROR";
>             break;
>         case 8:
>             responseCode = "TRANSACTION_EXPIRATION_ERROR";
>             break;
>         case 9:
>             responseCode = "SERVER_BUSY";
>             break;
>         case 10:
>             responseCode = "NO_CONNECTION";
>             break;
>         case 11:
>             responseCode = "NOT_ENOUGH_EFFECTIVE_CONNECTION";
>             break;
>         case 20:
>             responseCode = "OTHER_ERROR";
>             break;
>     }
>     return responseCode;
> }
> ```

hi, @godmonth 
really appreciate your comment.
the original code without the break statements is buggy,which will execute later branches till the end. Obviously, this is useless；
may fix it in the later release;

**Comment by angrynurd** [comment]
fixed in version 0.9.1 .
