### ISSUE TITLE
 getResult is always false

### ISSUE THREAD

**Issue by bai-xuan** [tronprotocol/trident#138]
use :

apiWrapper.freezeBalanceV2

The return is normal, but getResult is always false:

transactionExtention.getResult().getResult()

**Comment by endiaoekoe** [comment]
> use :
> 
> apiWrapper.freezeBalanceV2
> 
> The return is normal, but getResult is always false:
> 
> transactionExtention.getResult().getResult()

hi, @bai-xuan 
could you check what the response_code it return?
usually, when the field 'result' is true,the field 'response_code' will be SUCCESS.
but when getResult() is false,getResonseCode() will be like ‘OTHER_ERROR’ or other error codes.
below is the [codes ](https://github.com/tronprotocol/java-tron/blob/773b374cec6668bb75911357576a41221503f806/framework/src/main/java/org/tron/core/services/RpcApiService.java#L1106)of this function in the server side.
![image](https://github.com/user-attachments/assets/e828b08e-ebda-484b-b6f8-135cb1188a9b)

**Comment by bai-xuan** [comment]
![image](https://github.com/user-attachments/assets/0f248a09-5364-4d54-bcae-f115ab985a0d)

**Comment by endiaoekoe** [comment]
@bai-xuan 
I just walked through the codes of apiWrapper.freezeBalanceV2.in trident(client side), the most important thing function freezeBalanceV2() **only does** is  to construct the transaction;
so, when invoking function freezeBalanceV2, the result field represents whether the transaction was constructed successfully or not.
Obviously, It is a bug here.
btw,if you invoke apiWrapper.freezeBalanceV2 and does not throw any exceptions , it means the tx construct is successful and you can broadcast the tx to the chain;

**Comment by bai-xuan** [comment]
As you can see, no exceptions were thrown, so I conclude that this is a bug.

**Comment by angrynurd** [comment]
fixed in version 0.9.1.

**Comment by bai-xuan** [comment]
Received, currently reviewing. Thank you for handling it. If there are any follow-up issues, we will communicate again.
