### ISSUE TITLE
trc20 Multisign transactions

### ISSUE THREAD

**Issue by skysame** [tronprotocol/trident#141]
Hi team, I can't find any documentation related to using Trident to perform **_TRC20_** multi-signature transactions and **TRC20 to set active permissions**.
Can you show me the right documentation, or even a code example on how to do this on Trident?
Thanks in advance!

**Comment by angrynurd** [comment]
hi, @skysame 
please refer to this [issue](https://github.com/tronprotocol/trident/issues/141).

**Comment by skysame** [comment]
> hi, @skysame please refer to this [issue](https://github.com/tronprotocol/trident/issues/141).

Huh? My trc20 transfer is not trx transfer, I have tried many times but failed to succeed, I do not know how to set active permissions to initiate a transfer

**Comment by skysame** [comment]
> hi, @skysame please refer to this [issue](https://github.com/tronprotocol/trident/issues/141).
trc20 multi-signature transfer How do I write the code? How do I set active permissions?
I need your help.
`public static void testSendTrc20Transaction() {

        ApiWrapper client = ApiWrapper.ofNile("2c795db526aa8910572815d706aa0dfa6f11b3ce84711b09d83021c778f2621e");
        Function trc20Transfer = new Function("transfer",
                Arrays.asList(new Address("TUKHMQiVqoXCYZzrgG9Lx8xoTcg76E3YEn"),
                        new Uint256(BigInteger.valueOf(10).multiply(BigInteger.valueOf(10).pow(18)))),
                Arrays.asList(new TypeReference<Bool>() {}));

        String encodedHex = FunctionEncoder.encode(trc20Transfer);

        org.tron.trident.proto.Contract.TriggerSmartContract trigger =
                org.tron.trident.proto.Contract.TriggerSmartContract.newBuilder()
                        .setOwnerAddress(ApiWrapper.parseAddress("TJVRnkVDKmVsWKeYhrxgkPyxSSZZ9KFzmw"))
                        .setContractAddress(ApiWrapper.parseAddress("TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf"))
                        .setData(ApiWrapper.parseHex(encodedHex))
                        .build();
        Response.TransactionExtention txnExt = client.blockingStub.triggerContract(trigger);
        Chain.Transaction signedTxn = client.signTransaction(txnExt);
        KeyPair keyPair = new KeyPair("579a8d5806ccc38c7723ea689a818fc6980abb53f8515525c65896f2409311c0");
        Chain.Transaction signedTxnOne = client.signTransaction(txnExt,keyPair);
        Response.TransactionReturn ret = client.blockingStub.broadcastTransaction(signedTxnOne);
        System.out.println("======== Result ========\n" + ret.toString());
    }`

**Comment by angrynurd** [comment]
> do not know how to set active permissions

try Apiwrapper.accountPermissionUpdate(),for the details about how set the params of active permission,refer to this [doc](https://developers.tron.network/reference/accountpermissionupdate).

**Comment by skysame** [comment]
@endiaoekoe 
Hello, I mean how can transactions created in the code be initiated with an active identity when my account has been set with active permissions for multiple controlled accounts
