### ISSUE TITLE
Can any1 give me an example code about USDT transfer?

### ISSUE THREAD

**Issue by DuomiY** [tronprotocol/trident#18]
Can any1 give me an example code about USDT transfer? with trident, thinks~

**Comment by andreas-barthel** [comment]
You can try the USDT transfer example from the official documentation....
https://developers.tron.network/docs/interacting-with-smart-contracts-1

RTFM

**Comment by DuomiY** [comment]
> You can try the USDT transfer example from the official documentation....
> https://developers.tron.network/docs/interacting-with-smart-contracts-1
> 
> RTFM

I'v read and try, but I don't understand the flow, I just need an sample code to help me understand it, thanks.

**Comment by DuomiY** [comment]
> You can try the USDT transfer example from the official documentation....
> https://developers.tron.network/docs/interacting-with-smart-contracts-1
> 
> RTFM

I think many people need this sample code, so post the code here will help developers with coding

**Comment by andreas-barthel** [comment]
There are already code examples in the documentation. Especially for TRC-20 interaction there a nice examples.
https://developers.tron.network/docs/trc-20-contracts
No reason for copy and pasting here.

**Comment by DuomiY** [comment]
> There are already code examples in the documentation. Especially for TRC-20 interaction there a nice examples.
> https://developers.tron.network/docs/trc-20-contracts
> No reason for copy and pasting here.

Ok, I try again. Thanks

**Comment by DuomiY** [comment]
> There are already code examples in the documentation. Especially for TRC-20 interaction there a nice examples.
> https://developers.tron.network/docs/trc-20-contracts
> No reason for copy and pasting here.

I make it!! thanks~

**Comment by Starsakary** [comment]
Kindly close your issue if it's already solved.

**Comment by liangxingnian** [comment]
I try it，but return Validate signature error
