### ISSUE TITLE
Import wallet by mnemonic words

### ISSUE THREAD

**Issue by SembaMax** [tronprotocol/trident#19]
Hello,
When i checked Tron android app here https://developers.tron.network/docs/android-wallet
I see the ability of importing an existing wallet by mnemonic words.
Is this doable by using this library ? (i cannot find it in the documentation)
and if so, could you please refer to an example or a resource that clarifies the implementation ?

Thanks in advance!

**Comment by Starsakary** [comment]
Currently, there is no plan for mnemonic support functions.

You can try to make an implementation yourself. The path is m/44'/195'/0'/0/0.
