### ISSUE TITLE
Is there no transactionId in Chain.Transaction class ?

### ISSUE THREAD

**Issue by bluedusk** [tronprotocol/trident#32]
Hi team,

Is there no transactionId in Chain.Transaction class ?
How can I get transaction id from China.Transaction object then ? (Without using TransactionInfo).
Any particular reason transaction object does not have an ID ? 

Many Thanks.

**Comment by Starsakary** [comment]
Refer to [this](https://github.com/tronprotocol/trident/blob/main/trident-java/core/src/main/java/org/tron/trident/core/ApiWrapper.java#L214).
