### ISSUE TITLE
如何使用trident验证字符串格式的签名

### ISSUE THREAD

**Issue by zhuochujie** [tronprotocol/trident#39]
比如说我签名了"login"的Hex格式(0x6c6f67696e)
这是签名后的数据(0x4c8cf658a98a35e99919d37a22c2cdb0484c24c0c42f782b503f00a7451f2656401630a55d132cdf8550cef34f71a9ecca344eea55d7a7a9a49e33686b3c262c1b)
这是签名的地址(TVeXCKePw3vZCZqwnKvtt4z9EYsWwnXVcK)

怎么判断是不是这个地址签名的,直接调用verify方法是报错的,好像是tronweb在签名字符串的时候会添加\x19TRON Signed Message:\n32这段内容,希望能提供方法

**Comment by Cletitia** [comment]
trident目前仅能验证普通的字符串签名，和验证交易同理。添加header的字符串需先参考tronweb中的方式。
