### ISSUE TITLE
ApiWrapper.resolveResultCode bug

### ISSUE THREAD

**Issue by godmonth** [tronprotocol/trident#40]
org.tron.trident.core.ApiWrapper.resolveResultCode(int code){}
code sample:
        switch (code) {
            case 0:
                responseCode = "SUCCESS";
            case 1:
                responseCode = "SIGERROR";
           ....
            case 20:
                responseCode = "OTHER_ERROR";
        }
        return responseCode;
Each branch lacks a break or return statement, This causes any errors to be OTHER_ERROR.
Are you really test these codes？

**Comment by Starsakary** [comment]
This will be fixed then.
