### ISSUE TITLE
How to get transactions details like toAddress from block number ?

### ISSUE THREAD

**Issue by kunalransing** [tronprotocol/trident#42]
Hi,
I'm using below to get transactions from block number from testnet - Shasta
```
TransactionInfoList txList = wrapper.getTransactionInfoByBlockNum(20223386);
```
But here I'm not getting transaction details like toAddress, amount etc.
So I called below
```
Transaction tx = wrapper.getTransactionById("cfdde007f3775b390801baa3c97868435d62d4e7cb3ad48671571ca22b7f48ba");
```
But here also I don't see details like toAddress, amount etc
Please help me.
Thanks.

**Comment by Starsakary** [comment]
TRON takes Protocol Buffers for serialization. Take a look at the documentation of the Protocol Buffers.
