### ISSUE TITLE
Need sign message method

### ISSUE THREAD

**Issue by dongxicc** [tronprotocol/trident#46]
There is only a sign-transaction in trident but no sign-hex string 
In tronweb:
// sign a transaction
tronWeb.trx.sign(transaction, privateKey);

// or
// sign a Hex formatted string
tronWeb.trx.sign(str, privateKey)

**Comment by Starsakary** [comment]
https://github.com/tronprotocol/trident/blob/main/trident-java/core/src/main/java/org/tron/trident/core/key/KeyPair.java#L82
