### ISSUE TITLE
can this be used on android?

### ISSUE THREAD

**Issue by jackzhp** [tronprotocol/trident#47]
can this library be used on android?

java 13? android stick with java8, at lease the source code can not be compiled for android project. 
i guess library jar file should be ok. 

what does the team say?

**Comment by jackzhp** [comment]
at first, I was fighting with log4j,
and then 

java.security.NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC

relevant info is here: https://stackoverflow.com/questions/55123228/java-security-nosuchalgorithmexception-no-such-algorithm-ecdsa-for-provider-bc

can the team write down something on the readme page on how to use this on android?

**Comment by Starsakary** [comment]
References in an Android project will be the same as a Java project. This error does not seem to be related to trident itself.
