### ISSUE TITLE
How can I get the value of blockhash?

### ISSUE THREAD

**Issue by cloudlessa** [tronprotocol/trident#48]
`wrapper.getNowBlock().getBlockHeader().getRawData()`;this method can only get the parent hash,how should i get blockhash？ 
like this : (https://tronscan.io/) :<img width="664" alt="122" src="https://user-images.githubusercontent.com/20315613/158957125-03c19fe4-f14c-49dc-89a7-b36a1e66efad.png">

**Comment by Starsakary** [comment]
Responses of RPC APIs do not contain block IDs. Tronscan relies on HTTP APIs which return a `BlockCapsule` defined in java-tron. You may refer to this: [BlockCapsule.getBlockId](https://github.com/tronprotocol/java-tron/blob/develop/chainbase/src/main/java/org/tron/core/capsule/BlockCapsule.java#L198)

**Comment by cloudlessa** [comment]
ok,thanks.I will try it.
