### ISSUE TITLE
ApiWrapper 线程安全吗？可以在多线程环境下使用吗？

### ISSUE THREAD

**Issue by shiyuanfunc** [tronprotocol/trident#49]
业务中通过ApiWrapper来操作TRC20合约，但是这个实例可以在多线程环境下共享使用吗？还是每个线程需要创建自己的ApiWrapper实例对象呢？

**Comment by Cletitia** [comment]
每个实例绑定一个单独私钥，因此，你无法用同一个实例操作多个账户。
多个`ApiWrapper`的实例可能会导致错误，因此每个实例使用结束时，须调用其`close()`方法。
