### ISSUE TITLE
Method threw 'java.lang.NoSuchMethodError' exception. Cannot evaluate org.tron.trident.proto.Response$TransactionExtention.toString()

### ISSUE THREAD

**Issue by nieaima0** [tronprotocol/trident#51]
Method threw 'java.lang.NoSuchMethodError' exception. Cannot evaluate org.tron.trident.proto.Response$TransactionExtention.toString()

**Comment by nieaima0** [comment]
Method threw 'java.lang.NoClassDefFoundError' exception. Cannot evaluate org.tron.trident.proto.Chain$Transaction.toString()

**Comment by nieaima0** [comment]
Method threw 'java.lang.NoClassDefFoundError' exception. Cannot evaluate org.tron.trident.proto.Response$TransactionReturn.toString()

**Comment by Starsakary** [comment]
Kindly copy and paste your demo code here for analysis.
