### ISSUE TITLE
关于解码工具方法，是否考虑设为Public？

### ISSUE THREAD

**Issue by tianfangdao** [tronprotocol/trident#52]
官方文档：参数的类型在org.tron.trident.abi.datatypes中，请根据参数类型选择合适的对应java类。
https://cn.developers.tron.network/reference/encode-decode#%E5%8F%82%E6%95%B0%E7%BC%96%E7%A0%81

然而实际上 datatypes 当中，各类具体的解码方法都非public级别。
https://github.com/tronprotocol/trident/blob/168c1cd9e931a36657a9adfc39ec9b112a4f664e/trident-java/abi/src/main/java/org/tron/trident/abi/TypeDecoder.java#L97

**Comment by tianfangdao** [comment]
当前是这样解决的
![image](https://user-images.githubusercontent.com/48181427/160982847-6f307ca0-583e-42c4-ac3f-12686135dce1.png)

**Comment by Cletitia** [comment]
文档中只是示例。实际上，对数据的解码，只需要用到两个`public`方法。
