### ISSUE TITLE
文档上的estimateBandwidth(Transaction txn) 方法未提供

### ISSUE THREAD

**Issue by bannerxu** [tronprotocol/trident#54]
版本：0.3.0
文档：[https://cn.developers.tron.network/reference/apis-transactions#estimatebandwidth](https://cn.developers.tron.network/reference/apis-transactions#estimatebandwidth)
问题描述：在`ApiWrapper`中没有找到文档中对应的计算交易所需的带宽的方法

**Comment by Starsakary** [comment]
The code in branch `master` now correctly includes this method.

**Comment by bannerxu** [comment]
thank

**Comment by bannerxu** [comment]
> The code in branch `master` now correctly includes this method.

thank
