### ISSUE TITLE
getblockbynum获取到的交易是Chain.Transaction类型的，没有getTxid方法

### ISSUE THREAD

**Issue by wtf-boy** [tronprotocol/trident#56]
https://cn.developers.tron.network/reference/api-query-the-network#getblockbynum

**Comment by tianfangdao** [comment]
一起造轮子
```java
  /**
   * 解析交易ID（交易hash）
   *
   * @param transaction 交易
   * @return hash
   */
  public static String parseTxId(Chain.Transaction transaction) {
      byte[] rawData = transaction.getRawData().toByteArray();
      byte[] rawDataHash256 = Hash.sha256(rawData);
      return Hex.toHexString(rawDataHash256);
  }
```

**Comment by Cletitia** [comment]
`Transaction`中不包括`id`字段，`java-tron`在`Transaction`对象外面包装一层`capsule`，并在`capsule`里保存了交易id。
`ApiWrapper`里面已经包含了手动计算交易id的函数：https://github.com/tronprotocol/trident/blob/main/trident-java/core/src/main/java/org/tron/trident/core/ApiWrapper.java#L214
