### ISSUE TITLE
在读 Transaction交易时间的时候，总是出现时间戳为0的情况

### ISSUE THREAD

**Issue by ghost** [tronprotocol/trident#57]
![image](https://user-images.githubusercontent.com/48181427/162612484-cedd8fc8-83ba-45da-a0a5-a376eef150ff.png)

![image](https://user-images.githubusercontent.com/48181427/162612474-ca2db712-060d-44be-93ce-8f832211759d.png)

**Comment by tianfangdao** [comment]
测试获取单个交易的API也会出现此情况！
```java
Chain.Transaction transactionById = apiWrapper.getTransactionById("ID");
timestamp = transactionById.getRawData().getTimestamp();
log.debug("时间戳：{}", timestamp);
```

**Comment by Cletitia** [comment]
这个字段没有参考意义，忽略即可。

**Comment by tianfangdao** [comment]
> 测试获取单个交易的API也会出现此情况！
> 
> ```java
> Chain.Transaction transactionById = apiWrapper.getTransactionById("ID");
> timestamp = transactionById.getRawData().getTimestamp();
> log.debug("时间戳：{}", timestamp);
> ```

奇怪，重新测了一下，独立获取交易信息是能读到时间的。从块中拿到的依然没有，虽然知道所有交易时间=块产生时间。
暂时只能忽略掉
