### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by LemonCoding** [tronprotocol/trident#58]
直接在根目录下用要求的java和gradle进行编译打包（gradle build），生成的jar包很小，也没办法调用里面的类，是为什么呢？

**Comment by Cletitia** [comment]
进入到trident-java下再进行打包，并分别在abi, core和utils中分别找到三个jar文件。

**Comment by tangguo0039** [comment]
你好能帮我看看吗？

Plugin with id 'maven' not found.

23:42:11: Executing task 'build'...


FAILURE: Build failed with an exception.

* Where:
Build file 'D:\github\ziyuanwendang\trident\trident-java\build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'trident'.
> Plugin with id 'maven' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 190ms
Plugin with id 'maven' not found.
Open File
23:42:11: Task execution finished 'build'.

**Comment by Benson0224** [comment]
close this issue as no update for a long time.

Feel free to re-open it if you still see the issue. thanks.
