### ISSUE TITLE
HD Wallets

### ISSUE THREAD

**Issue by mmahdisz** [tronprotocol/trident#60]
Hi,
Thank you for your great contributions.

I couldn't find how I can make HD Wallets. Is that possible?

**Comment by xq-lu** [comment]
> Hi, Thank you for your great contributions.
> 
> I couldn't find how I can make HD Wallets. Is that possible?

sorry to reply late.i am not sure what you mean for 'make HD Wallets',could you provide more details?

**Comment by mmahdisz** [comment]
Hi,
I need to create child pair keys based on a specific master key. As you can see in TronLink App and Extension, an option exists to create addresses from HD Wallet.

Python Library for the same operation, Tron wallets included:
https://github.com/meherett/python-hdwallet

Detail About HDWallet:
https://www.investopedia.com/terms/h/hd-wallet-hierarchical-deterministic-wallet.asp

TronLink Extension HD Wallet Support:

![image](https://user-images.githubusercontent.com/29574424/224958341-b6f67044-d108-4dd4-bd74-928522a88b43.png)
![image](https://user-images.githubusercontent.com/29574424/224958320-8d6c06e5-26c1-41a8-a918-275e0c1a1955.png)

**Comment by xq-lu** [comment]
> Hi, Thank you for your response. I need to create child pair keys based on a specific master key. As you can see in TronLink App and Extension, an option exists to create addresses from HD Wallet.
> 
> Python Library for the same operation, Tron wallets included: https://github.com/meherett/python-hdwallet
> 
> Detail About HDWallet: https://www.investopedia.com/terms/h/hd-wallet-hierarchical-deterministic-wallet.asp
> 
> TronLink Extension HD Wallet Support:
> 
> ![image](https://user-images.githubusercontent.com/29574424/224958341-b6f67044-d108-4dd4-bd74-928522a88b43.png) ![image](https://user-images.githubusercontent.com/29574424/224958320-8d6c06e5-26c1-41a8-a918-275e0c1a1955.png)

hi,mmahdisz
we will consider your request about implementing HD wallets in trident-java.
