### ISSUE TITLE
使用trident-java部署官方示例合约异常

### ISSUE THREAD

**Issue by mengzhaoxu99** [tronprotocol/trident#61]
使用trident-java部署官方示例合约异常

官方demo地址：https://cn.developers.tron.network/reference/encode-decode

      public static void main(String[] args) {
                try {
                    ApiWrapper wrapper = ApiWrapper.ofShasta("此处密钥");
                    String bytecode = "608060405234801561001057600080fd5b50d3801561001d57600080fd5b50d2801561002a57600080fd5b506040516103e73803806103e7833981016040819052610049916100fc565b805161005c906000906020840190610063565b505061021c565b82805461006f906101cb565b90600052602060002090601f01602090048101928261009157600085556100d7565b82601f106100aa57805160ff19168380011785556100d7565b828001600101855582156100d7579182015b828111156100d75782518255916020019190600101906100bc565b506100e39291506100e7565b5090565b5b808211156100e357600081556001016100e8565b6000602080838503121561010f57600080fd5b82516001600160401b038082111561012657600080fd5b818501915085601f83011261013a57600080fd5b81518181111561014c5761014c610206565b604051601f8201601f19908116603f0116810190838211818310171561017457610174610206565b81604052828152888684870101111561018c57600080fd5b600093505b828410156101ae5784840186015181850187015292850192610191565b828411156101bf5760008684830101525b98975050505050505050565b600181811c908216806101df57607f821691505b6020821081141561020057634e487b7160e01b600052602260045260246000fd5b50919050565b634e487b7160e01b600052604160045260246000fd5b6101bc8061022b6000396000f3fe608060405234801561001057600080fd5b50d3801561001d57600080fd5b50d2801561002a57600080fd5b50600436106100455760003560e01c8063ef690cc01461004a575b600080fd5b610052610068565b60405161005f91906100f6565b60405180910390f35b600080546100759061014b565b80601f01602080910402602001604051908101604052809291908181526020018280546100a19061014b565b80156100ee5780601f106100c3576101008083540402835291602001916100ee565b820191906000526020600020905b8154815290600101906020018083116100d157829003601f168201915b505050505081565b600060208083528351808285015260005b8181101561012357858101830151858201604001528201610107565b81811115610135576000604083870101525b50601f01601f1916929092016040019392505050565b600181811c9082168061015f57607f821691505b6020821081141561018057634e487b7160e01b600052602260045260246000fd5b5091905056fea26474726f6e582212202fd21f25d376482dcf6eebcd0a0ccb46d5f2547161e2403008fc4ce7b7f1c90464736f6c63430008060033";
                    //Please add "entrys" before the compiled bytecode,
                    //and add escape characters in the json string
                    String abi = "{\"entrys\":[{\"inputs\":[{\"internalType\":\"string\",\"name\":\"message\",\"type\":\"string\"}],\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"},{\"inputs\":[],\"name\":\"greeting\",\"outputs\":[{\"internalType\":\"string\",\"name\":\"\",\"type\":\"string\"}],\"stateMutability\":\"view\",\"type\":\"function\"}]}";
                    Contract cntr = new Contract.Builder()
                            .setOwnerAddr(ApiWrapper.parseAddress("TTtjiZbTWZkkSkze5BUKMtGrmckcEs9qZp"))
                            .setOriginAddr(ApiWrapper.parseAddress("TTtjiZbTWZkkSkze5BUKMtGrmckcEs9qZp"))
                            .setBytecode(ByteString.copyFrom(Numeric.hexStringToByteArray(bytecode)))
                            .setAbi(abi)
                            .build();
                    cntr.setWrapper(wrapper); //set ApiWrapper with your private key
                    List params = new ArrayList<Type>();
                    params.add(new Utf8String("mzxtest")); //encode params
                    TransactionBuilder builder = cntr.deploy(params); //set params
                    builder.setFeeLimit(1000000000L); //set feelimit
                    Chain.Transaction signedTxn = wrapper.signTransaction(builder.build()); //sign transaction
                    String ret = wrapper.broadcastTransaction(signedTxn); //broadcast transaction
                    System.out.println("======== Result ========\n" + ret); //print the transaction hash, only for display
                } catch (Exception e) {
                    e.printStackTrace();
                }
        }

运行结果：

    ======== Result ========
    1f91f70e765cb63d46e651b367998ca0f9b11f50e79aa0a84f24666c92edc58c

**Comment by mengzhaoxu99** [comment]
上述abi及bytecode通过http api的方式则可以部署成功。

其中的参数按照官方文档中：https://cn.developers.tron.network/reference/wallet-deploycontract

parameter
string
传递给合约构造函数的参数。 调用参数[1、2]的虚拟机格式，使用remix提供的js工具，将合同调用方调用的参数数组[1、2]转换为虚拟机所需的参数格式。

使用web3j的手动编码方式传递，运行结果为：

具体代码为：

    package contorller;
    
    import cn.hutool.http.HttpRequest;
    import cn.hutool.json.JSONUtil;
    import org.web3j.abi.FunctionEncoder;
    import org.web3j.abi.datatypes.Type;
    import org.web3j.abi.datatypes.Utf8String;
    import org.web3j.abi.datatypes.generated.Uint256;
    import org.web3j.abi.datatypes.generated.Uint8;
    
    import java.util.ArrayList;
    import java.util.List;
    
    public class Test2 {
    
        public static String encoderAbi(){
            List<Type> inputParameters = new ArrayList<>();
            inputParameters.add(new Utf8String("mzx"));
            return FunctionEncoder.encodeConstructor(inputParameters);
        }
        public static void main(String[] args) {
            TronContractRequestDto tronContractRequestDto = new TronContractRequestDto();
            tronContractRequestDto.setOwner_address("41C499D30A4FAA2550C06889EB0389873954D7669D");
            tronContractRequestDto.setAbi("[{\"inputs\":[{\"internalType\":\"string\",\"name\":\"message\",\"type\":\"string\"}],\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"},{\"inputs\":[],\"name\":\"greeting\",\"outputs\":[{\"internalType\":\"string\",\"name\":\"\",\"type\":\"string\"}],\"stateMutability\":\"view\",\"type\":\"function\"}]");
            tronContractRequestDto.setBytecode("608060405234801561001057600080fd5b50d3801561001d57600080fd5b50d2801561002a57600080fd5b506040516103e73803806103e7833981016040819052610049916100fc565b805161005c906000906020840190610063565b505061021c565b82805461006f906101cb565b90600052602060002090601f01602090048101928261009157600085556100d7565b82601f106100aa57805160ff19168380011785556100d7565b828001600101855582156100d7579182015b828111156100d75782518255916020019190600101906100bc565b506100e39291506100e7565b5090565b5b808211156100e357600081556001016100e8565b6000602080838503121561010f57600080fd5b82516001600160401b038082111561012657600080fd5b818501915085601f83011261013a57600080fd5b81518181111561014c5761014c610206565b604051601f8201601f19908116603f0116810190838211818310171561017457610174610206565b81604052828152888684870101111561018c57600080fd5b600093505b828410156101ae5784840186015181850187015292850192610191565b828411156101bf5760008684830101525b98975050505050505050565b600181811c908216806101df57607f821691505b6020821081141561020057634e487b7160e01b600052602260045260246000fd5b50919050565b634e487b7160e01b600052604160045260246000fd5b6101bc8061022b6000396000f3fe608060405234801561001057600080fd5b50d3801561001d57600080fd5b50d2801561002a57600080fd5b50600436106100455760003560e01c8063ef690cc01461004a575b600080fd5b610052610068565b60405161005f91906100f6565b60405180910390f35b600080546100759061014b565b80601f01602080910402602001604051908101604052809291908181526020018280546100a19061014b565b80156100ee5780601f106100c3576101008083540402835291602001916100ee565b820191906000526020600020905b8154815290600101906020018083116100d157829003601f168201915b505050505081565b600060208083528351808285015260005b8181101561012357858101830151858201604001528201610107565b81811115610135576000604083870101525b50601f01601f1916929092016040019392505050565b600181811c9082168061015f57607f821691505b6020821081141561018057634e487b7160e01b600052602260045260246000fd5b5091905056fea26474726f6e582212202fd21f25d376482dcf6eebcd0a0ccb46d5f2547161e2403008fc4ce7b7f1c90464736f6c63430008060033");
            tronContractRequestDto.setFee_limit(1000000000);
            tronContractRequestDto.setOrigin_energy_limit(100000);
            tronContractRequestDto.setName("AngryToken");
            tronContractRequestDto.setCall_value(0);
            String s = encoderAbi();
            tronContractRequestDto.setParameter(s);
            tronContractRequestDto.setConsume_user_resource_percent(100);
            String body = HttpRequest.post("https://api.shasta.trongrid.io/wallet/deploycontract")
                    .body(JSONUtil.toJsonStr(tronContractRequestDto))
                    .execute().body();
            System.out.println(body);
    
            TronContractSignRequestDto tronContractSignRequestDto = new TronContractSignRequestDto();
            tronContractSignRequestDto.setPrivateKey("私钥脱敏");
            tronContractSignRequestDto.setTransaction(body);
            String body1 = HttpRequest.post("https://api.shasta.trongrid.io/wallet/gettransactionsign")
                    .body(JSONUtil.toJsonStr(tronContractSignRequestDto))
                    .execute().body();
            System.out.println(body1);
            String body2 = HttpRequest.post("https://api.shasta.trongrid.io/wallet/broadcasttransaction")
                    .body(body1)
                    .execute().body();
            System.out.println(body2);
        }
    }
    

运行结果为：

    {"result":true,"txid":"22095ab58088c75af2d8f8d472709b3336f01c8b895a2501e0edf2a088a882fd"}

**Comment by ethan1844** [comment]
This issue will be closed as no update for a long time, please feel free to re-open it if you still see the issue, thanks.
