### ISSUE TITLE
依赖更新

### ISSUE THREAD

**Issue by Aiden-777** [tronprotocol/trident#62]
依赖包：
```
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-all</artifactId>
    <version>1.48.0</version>
</dependency>
```
里层依赖：
```
<dependency>
  <groupId>io.grpc</groupId>
  <artifactId>grpc-xds</artifactId>
  <version>1.48.0</version>
  <scope>compile</scope>
</dependency>
```
grpc-xds下原本还有这个依赖包： `org.bouncycastle.bcpkix-jdk15on`，
最新版 1.48.0 已经去除了（已知1.47.0可用），大佬们是否考虑更新一下？
trident项目使用：https://github.com/tronprotocol/trident/search?q=import+org.bouncycastle

**Comment by Joker-AAA** [comment]
https://github.com/grpc/grpc-java/releases/tag/v1.48.0
xds: Remove unused org.bouncycastle:bcpkix-jdk15on dependency

**Comment by Joker-AAA** [comment]
使用最新版grpc依赖的当前解决办法，单独添加编码库：
```
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-all</artifactId>
    <version>1.48.1</version>
</dependency>

<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk18on</artifactId>
    <version>1.71</version>
</dependency>
```
测试无异常

**Comment by zjkal** [comment]
不管使用1.48.1还是1.47.0, 都报找不到文件, 有点崩溃
`Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/stub/AbstractStub
	at org.example.Main.main(Main.java:9)
Caused by: java.lang.ClassNotFoundException: io.grpc.stub.AbstractStub
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
`

**Comment by Aiden-777** [comment]
> 不管使用1.48.1还是1.47.0, 都报找不到文件, 有点崩溃 `Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/stub/AbstractStub at org.example.Main.main(Main.java:9) Caused by: java.lang.ClassNotFoundException: io.grpc.stub.AbstractStub at java.net.URLClassLoader.findClass(URLClassLoader.java:387) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ... 1 more `

1.48.1 需要单独引入编码库，上面已经给出。
加上trident三个包，总共5个包，确保maven正确下载了依赖。

```java
 <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-all</artifactId>
            <version>1.49.2</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>1.72</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.tron.trident</groupId>
            <artifactId>abi</artifactId>
            <version>0.3.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.tron.trident</groupId>
            <artifactId>utils</artifactId>
            <version>0.3.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.tron.trident</groupId>
            <artifactId>core</artifactId>
            <version>0.3.0</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by Aiden-777** [comment]
> 不管使用1.48.1还是1.47.0, 都报找不到文件, 有点崩溃 `Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/stub/AbstractStub at org.example.Main.main(Main.java:9) Caused by: java.lang.ClassNotFoundException: io.grpc.stub.AbstractStub at java.net.URLClassLoader.findClass(URLClassLoader.java:387) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ... 1 more `

1.48.1 需要单独引入编码库，上面已经给出。
加上trident三个包，总共5个包，确保maven正确加载了依赖。

```java
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-all</artifactId>
            <version>1.49.2</version>
        </dependency>

        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>1.72</version>
        </dependency>

        <dependency>
            <groupId>org.tron.trident</groupId>
            <artifactId>abi</artifactId>
            <version>0.3.0</version>
        </dependency>

        <dependency>
            <groupId>org.tron.trident</groupId>
            <artifactId>utils</artifactId>
            <version>0.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.tron.trident</groupId>
            <artifactId>core</artifactId>
            <version>0.3.0</version>
        </dependency>
```

**Comment by zjkal** [comment]
已经搞定了, 非常感谢
