### ISSUE TITLE
不兼容的类型: org.tron.trident.core.key.KeyPair无法转换为java.util.List<java.lang.String>

### ISSUE THREAD

**Issue by zycshiniye** [tronprotocol/trident#65]
我更新了依赖包 0.3.0 编译 爆这个错误!!!
可以问下是什么问题吗?

**Comment by xq-lu** [comment]
你的描述已经说清楚了，org.tron.trident.core.key.KeyPair和java.util.List是不兼容的类型，无法转换。你可以尝试下刷新下依赖，在build

**Comment by ethan1844** [comment]
This issue will be closed as no update for a long time, please feel free to re-open it if you still see the issue, thanks.
