### ISSUE TITLE
When generating .jar files from core module only sources are generated. 

### ISSUE THREAD

**Issue by sench93** [tronprotocol/trident#68]
When generating .jar files from core module only sources are generated. The actual jar is not generated

**Comment by xq-lu** [comment]
if you use IDE(eg:IntelliJ Idea ) to develop,go to Gradle view,and click build button in t Tasks menu.it will build your souce code and generate the jar file,or you can click 'jar' button to generate jar file only.

**Comment by ethan1844** [comment]
This issue will be closed as no update for a long time, please feel free to re-open it if you still see the issue, thanks.
