### ISSUE TITLE
Trc20Contract transfer return OTHER_ERROR Validate signature error

### ISSUE THREAD

**Issue by liangxingnian** [tronprotocol/trident#69]
调用trident的transfer方法，结果返回Validate signature error

**Comment by liangxingnian** [comment]
please help

**Comment by liangxingnian** [comment]
![image](https://user-images.githubusercontent.com/41367396/222023949-09266170-3123-481a-83c2-347057680599.png)

**Comment by liukai1055** [comment]
请问你怎么解决的，我也出现了这个问题，感谢
