### ISSUE TITLE
I need to parse the response,but no documentation tells me the meaning of the attribute.

### ISSUE THREAD

**Issue by xiaoizichao** [tronprotocol/trident#7]
txId:efde2ab4d7522f67c5bd3c5bf546d2112a4004fe76d45db2d5b94334b8077878

**Comment by xiaoizichao** [comment]
trident getTransactionInfoById response:
id: "\357\336*\264\327R/g\305\275<[\365F\322\021*@\004\376v\324]\262\325\271C4\270\axx"
fee: 1231300
blockNumber: 29129143
blockTimeStamp: 1617807429000
contractResult: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
contract_address: "A\246\024\370\003\266\375x\t\206\244,x\354\234\177w\346\336\321<"
receipt {
  energy_fee: 1231300
  origin_energy_usage: 5836
  energy_usage_total: 14631
  net_usage: 351
  result: SUCCESS
}
log {
  address: "\246\024\370\003\266\375x\t\206\244,x\354\234\177w\346\336\321<"
  topics: "\335\362R\255\033\342\310\233i\302\260h\3747\215\252\225+\247\361c\304\241\026(\365ZM\365#\263\357"
  topics: "\000\000\000\000\000\000\000\000\000\000\000\000ybX\277\275#\3228\243\004\373T\333\2705\267qK\2010"
  topics: "\000\000\000\000\000\000\000\000\000\000\000\000\210\273\217\312\333\362\236\351\r\377\274\214\177\321\340*H_\276\377"
  data: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\017B@"
}

**Comment by xiaoizichao** [comment]
https://tronscan.org/#/transaction/efde2ab4d7522f67c5bd3c5bf546d2112a4004fe76d45db2d5b94334b8077878 response:
![image](https://user-images.githubusercontent.com/27492132/114366008-99fbde00-9bad-11eb-8348-d105070d0147.png)
I can't be like in the picture analyzing "Topics" and "Data",help me ?

**Comment by xiaoizichao** [comment]
@Sh11thead @jiangyy0824

**Comment by Starsakary** [comment]
1. The data you saw as "\000\000\000\000\" is because of the 'toString' method of Protobuf prints data in octal format.
2. Try the accessor methods to get specific fields and convert those hexadecimal strings to human-readable text.

**Comment by xiaoizichao** [comment]
topics:ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef

**Comment by xiaoizichao** [comment]
"topics": [
                "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "000000000000000000000000796258bfbd23d238a304fb54dbb835b7714b8130",
                "00000000000000000000000088bb8fcadbf29ee90dffbc8c7fd1e02a485fbeff"
            ]

topics[0] What is it?

**Comment by xiaoizichao** [comment]
![image](https://user-images.githubusercontent.com/27492132/114381653-efd88200-9bbd-11eb-8e26-2e9946f1ba26.png)

**Comment by xiaoizichao** [comment]
"data": "00000000000000000000000000000000000000000000000000000000000f4240"

**Comment by xiaoizichao** [comment]
"data": "00000000000000000000000000000000000000000000000000000000000f4240"
How do I analyze it

**Comment by xiaoizichao** [comment]
Is anyone here? Can you help me?

**Comment by xiaoizichao** [comment]
Are all the people who developed this purpose dead?

**Comment by juzi-code** [comment]
> "topics": [
> "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
> "000000000000000000000000796258bfbd23d238a304fb54dbb835b7714b8130",
> "00000000000000000000000088bb8fcadbf29ee90dffbc8c7fd1e02a485fbeff"
> ]
> 
> ### **topics[0] What is it?**
> topics[1] formAddress
> topics[2] toAddress

大佬，这个topics的数据你知道怎么解析吗？
