### ISSUE TITLE
Some grammatical error

### ISSUE THREAD

**Issue by all-creator** [tronprotocol/trident#73]
<img width="451" alt="Снимок экрана 2023-03-18 в 13 48 04" src="https://user-images.githubusercontent.com/67869113/226100961-ace7e0d1-bde2-4c1c-80fb-9e0105c75eeb.png">

in these places, "SUCESS" is indicated instead of "SUCCESS", but in some others, "SUCCESS" is indicated correctly, it's a bit confusing :)

**Comment by xq-lu** [comment]
> <img alt="Снимок экрана 2023-03-18 в 13 48 04" width="451" src="https://user-images.githubusercontent.com/67869113/226100961-ace7e0d1-bde2-4c1c-80fb-9e0105c75eeb.png">
> 
> in these places, "SUCESS" is indicated instead of "SUCCESS", but in some others, "SUCCESS" is indicated correctly, it's a bit confusing :)

hi,all-creator.
really appreciate correcting the wrong spelling in this project. the word 'SUCESS' is truly a misspelling, we will correct it.

**Comment by ethan1844** [comment]
This issue will be closed as no update for a long time, please feel free to re-open it if you still see the issue, thanks.
