### ISSUE TITLE
Packaged file name version is still 0.3.0

### ISSUE THREAD

**Issue by Aiden-777** [tronprotocol/trident#74]
Hi there, I noticed that when I package the library, the file name version remains at 0.3.0 even though there have been updates to the library since then. This can be confusing for users who are expecting a newer version.

Could you please update the packaged file name version to reflect the current version of the library? This will make it easier for users to identify which version they are using and ensure that they have access to the latest features and bug fixes.

Thanks for your attention to this matter.

**Comment by xq-lu** [comment]
> Hi there, I noticed that when I package the library, the file name version remains at 0.3.0 even though there have been updates to the library since then. This can be confusing for users who are expecting a newer version.
> 
> Could you please update the packaged file name version to reflect the current version of the library? This will make it easier for users to identify which version they are using and ensure that they have access to the latest features and bug fixes.
> 
> Thanks for your attention to this matter.

hi, Aiden-777.
really appreciate your pointing out this issue, we will make a fix soon.

**Comment by mikeluxue** [comment]
> Hi there, I noticed that when I package the library, the file name version remains at 0.3.0 even though there have been updates to the library since then. This can be confusing for users who are expecting a newer version.
> 
> Could you please update the packaged file name version to reflect the current version of the library? This will make it easier for users to identify which version they are using and ensure that they have access to the latest features and bug fixes.
> 
> Thanks for your attention to this matter.
hi, Aiden-777.
this issue has been fixed in the latest release.

**Comment by xq-lu** [comment]
> Hi there, I noticed that when I package the library, the file name version remains at 0.3.0 even though there have been updates to the library since then. This can be confusing for users who are expecting a newer version.
> 
> Could you please update the packaged file name version to reflect the current version of the library? This will make it easier for users to identify which version they are using and ensure that they have access to the latest features and bug fixes.
> 
> Thanks for your attention to this matter.
hi, Aiden-777.
this issue has been fixed in the latest issue.

**Comment by xq-lu** [comment]
> Hi there, I noticed that when I package the library, the file name version remains at 0.3.0 even though there have been updates to the library since then. This can be confusing for users who are expecting a newer version.
> 
> Could you please update the packaged file name version to reflect the current version of the library? This will make it easier for users to identify which version they are using and ensure that they have access to the latest features and bug fixes.
> 
> Thanks for your attention to this matter.

hi, Aiden-777.
this issue has been fixed in the latest issue.
