### ISSUE TITLE
About transfer in trident-java

### ISSUE THREAD

**Issue by ValarMorghulisMaiDou** [tronprotocol/trident#79]
Hi, I use trident-java to create transaction, but it was an error reported.

I code like this:  Response.TransactionExtention transaction = wrapper.transfer(fromAccount, toAccount, sunAmount);

And I receive these: 

(1) org.tron.trident.core.exceptions.IllegalException: createTransactionExtention error,UNIMPLEMENTED: Method not found: protocol.WalletSolidity/GetNowBlock2 at Main.transferTRX(Main.java:126)

(2) Caused by: org.tron.trident.core.exceptions.IllegalException: createTransactionExtention error,UNIMPLEMENTED: Method not found: protocol.WalletSolidity/GetNowBlock2

But isn't solidity already abandoned? Why it still reported errors related to solidity? 

Thank you very much.

**Comment by Ocea91** [comment]
![image](https://user-images.githubusercontent.com/114645811/233024413-6b9e0693-c281-4ea4-bf94-bed6fa77605f.png)
try to use the Trongrid official URL to set `TRONGRID_MAIN_NET_SOLIDITY` and see if the errors still persist.

**Comment by ValarMorghulisMaiDou** [comment]
Thank you. But I think I should explain the problem more clearly.

We have a Tron private chain and wanted to test it with trident-java SDK.

1. We build a full node by ourselves. The grpcEndpoint is the RPC address of our full node. Since solidity node has been abandoned, what should grpcEndpointSolidity be filled in?

2. We use SDK according to the official tutorial to initiate a transaction to our full node node, but an UNIMPLEMENTED error occurs. As described in my last question. 

But if we use the official RPC address, we can't detect our own nodes. So how do we solve this problem?

Thank you very much.

**Comment by ValarMorghulisMaiDou** [comment]
OK, it's done. Thank you very much!
