### ISSUE TITLE
about"getTransactionById"Return value

### ISSUE THREAD

**Issue by qq335103060** [tronprotocol/trident#8]
raw_data {
  ref_block_bytes: "k+"
  ref_block_hash: "\277\370d\321\356)\272F"
  expiration: 1618832860451
  contract {
    type: TriggerSmartContract
    parameter {
      type_url: "type.googleapis.com/protocol.TriggerSmartContract"
      value: "\n\025A(\216Z\335\312S0LG\326YZ\2338\301\373\260\"*\232\022\025A\246\024\370\003\266\375x\t\206\244,x\354\234\177w\346\336\321<\"D\251\005\234\273\000\000\000\000\000\000\000\000\000\000\000A\r\a\a\2269R\362\373\245\235\320o+BZ\316@\264\222\376\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\001\277\b\352\377"
    }
  }
  fee_limit: 10000000
}
signature: "\377\350\342gt#\311J\234\312uV\331\374\274CU\252\030\333f6\rs\343\366\021\025\215\246\246\004\365\'\337(\206n\2253\377\204LD \210\303\263\335\332\000y\f\227\241\356\275\r\306]\322\213\250\201\001"
ret {
  contractRet: SUCCESS
}
decode value：0a1541288e5addca53304c47d6595a9b38c1fbb0222a9a121541a614f803b6fd780986a42c78ec9c7f77e6ded13c2244a9059cbb0000000000000000000000410d0707963952f2fba59dd06f2b425ace40b492fe00000000000000000000000000000000000000000000000000000001bf08eaff
Self understanding：
0a15
41288e5addca53304c47d6595a9b38c1fbb0222a9a
1215
41a614f803b6fd780986a42c78ec9c7f77e6ded13c
2244
a9059cbb0000000000000000000000410d0707963952f2fba59dd06f2b425ace40b492fe00000000000000000000000000000000000000000000000000000001bf08eaff
I can't understand 0a15，1215，2244What is it?How to analyze？

**Comment by cathy-lishipu** [comment]
You can refer to this document: https://developers.tron.network/docs/apis

**Comment by qq335103060** [comment]
wrapper.toHex() Transcoding gets D：
0a1541288e5addca53304c47d6595a9b38c1fbb0222a9a121541a614f803b6fd780986a42c78ec9c7f77e6ded13c2244a9059cbb0000000000000000000000410d0707963952f2fba59dd06f2b425ace40b492fe00000000000000000000000000000000000000000000000000000001bf08eaff

**Comment by qq335103060** [comment]
0a15
41288e5addca53304c47d6595a9b38c1fbb0222a9a
1215
41a614f803b6fd780986a42c78ec9c7f77e6ded13c
2244
a9059cbb0000000000000000000000410d0707963952f2fba59dd06f2b425ace40b492fe00000000000000000000000000000000000000000000000000000001bf08eaff
I can't understand 0a15，1215，2244What is it?How to analyze？

**Comment by qq335103060** [comment]
Can I only intercept strings？

**Comment by qq335103060** [comment]
raw_data {
  ref_block_bytes: "\370\225"
  ref_block_hash: "\257\246\235\b;h\n\206"
  expiration: 1618909860000
  contract {
    type: TransferContract
    parameter {
      type_url: "type.googleapis.com/protocol.TransferContract"
      value: "\n\025A\266\367sY\347P\326\270\361\3047v\2735\234|\036(\217\360\022\025A\201h\202a\350\021\330_\a\2378\321R\375\027Yj\236\341\355\030\200\233\356\002"
    }
  }
  timestamp: 1618909802242
}
signature: "\270\004\'P\362\356\235\221\360f\330S\250\000\324\237S\242\355\344.P\350\224\356\3522K4R\b\222\215\n^\313\373\026\\G\r\2113\\~8`kr\300\262*\235\364\001\023\3757\305\213\352\2356S\001"
ret {
  contractRet: SUCCESS
}

value transcoding ：0a1541b6f77359e750d6b8f1c43776bb359c7c1e288ff012154181688261e811d85f079f38d152fd17596a9ee1ed18809bee02
protocol.TransferContract How to get transaction amount？

**Comment by Starsakary** [comment]
Cathy has given you the exact demo of decoding the value.

0a : type = byte, field_id = 1, 15: length = 0x15(21bytes)
12 : type = byte, field_id = 2, 15 : length = 0x15

You don't have to know the details of the decoding rules as Protobuf has already given you the function to decode the value in a single line. 

However, if you are still interested in what does these mean, refer to the protobuf encoding rules.

**Comment by qq335103060** [comment]
trident Yes no yes Decoding demonstration Code ？

**Comment by qq335103060** [comment]
Help me. What should I do？
