### ISSUE TITLE
该版本如何获取事件呢？

### ISSUE THREAD

**Issue by stepfensw** [tronprotocol/trident#80]
我准备获取某个合约的历史交易信息。但是我找了一般源码没有发现类似 像web3j  ethGetLogs 这样的方法

**Comment by LauraYH** [comment]
@stepfensw no, I don't think there is such an API or similar ones in trident.

**Comment by ExOCeo** [comment]
https://cn.developers.tron.network/docs/event-subscription   Trident应该是没有这样的方法，可以用插件。

**Comment by stepfensw** [comment]
好的.感谢. @ExOCeo
