### ISSUE TITLE
TRC20Contracts init error

### ISSUE THREAD

**Issue by isaguler** [tronprotocol/trident#82]
I am trying to interact with TRC20 Tokens inside my java app on Nile Testnet with trident.

I am looking for this docs: https://developers.tron.network/reference/trc-20-contracts
Apiwrapper wrapper = Apiwrapper.ofNile("...");
Contract contract = wrapper.getContract("contract address");
Trc20Contract token = new Trc20Contract(contract, "caller's address", wrapper);

And I am getting contract address information from "https://nile.tronscan.org/" .

when I try to use "token.decimals()" etc. I am getting "Invalid address: " error. Is this error caused by Nile Testnet or tronprotocol/trident.

**Comment by ExOCeo** [comment]
Just tried with USDT contract on Nile, and no problem, maybe you could go with another address and see if it works, otherwise, the problem would be the address you passed.....

**Comment by isaguler** [comment]
> Just tried with USDT contract on Nile, and no problem, maybe you could go with another address and see if it works, otherwise, the problem would be the address you passed.....

Thank you for your answer. I tried with USDT, BYY, JST on Nile Testnet and I got contract info from "https://nile.tronscan.org/" as I said. I am using api,util,core 0.5.0 btw. Can you share the contract address you used on your test case if possible. Also "caller's address" in Trc20Contract constructor I tried both "owner address of contract" and my account address (in org.tron.trident.core.contract "public Trc20Contract(Contract cntr, String ownerAddr, ApiWrapper wrapper)"), both failed.

**Comment by ExOCeo** [comment]
USDT contract address on Nile is `TDZDd58a44n5Bvg7pFpcdWhZpv7XsT9PsU`, the caller's address is your address, not the address of the contract issuer.

**Comment by isaguler** [comment]
> USDT contract address on Nile is `TDZDd58a44n5Bvg7pFpcdWhZpv7XsT9PsU`, the caller's address is your address, not the address of the contract issuer.

Thank you very much for your help. I guess it was about wrong contract address from "https://nile.tronscan.org/" . I got the token info now. Thanks!
