### ISSUE TITLE
com.google.protobuf.ByteString To Readable Response

### ISSUE THREAD

**Issue by isaguler** [tronprotocol/trident#84]
I query transaction with;
```
Chain.Transaction transaction = ApiWrapper.getTransactionById("b4d76f7e875836737cb373043250d8912048bcfe0bc981d6462adbb2e0c46c7f");
```
```
raw_data {
  ref_block_bytes: "X\236"
  ref_block_hash: "0\302\000\020\321C\016\247"
  expiration: 1683639822000
  contract {
    type: TransferContract
    parameter {
      type_url: "type.googleapis.com/protocol.TransferContract"
      value: "\n\025A\334\364\205\302\342\264\273\331\350[\203t\246\267\021\330#\271\313\002\022\025A\222\213\"#\260\220hn\021\331S\341b\2165\033\\2\226\317\030\300\204="
    }
  }
  timestamp: 1683639761857
}
signature: "3\360\003W\215\035\223Te\334\331\000{\360\243\223\a\274\246\237\303\313,P\303?\2342^Lz\033|x!\254Q\311+y\265\264\301~\006q\301\325E\231\276\2605\224\354\313\232\254\310\2768\025\376\247\001"
ret {
  contractRet: SUCCESS
}
```

Then I am getting value with;
```
ByteString value = transaction.getRawData.getContract(0).getParameter().getValue();
```
```
<ByteString@4536f341 size=50 contents="\n\025A\334\364\205\302\342\264\273\331\350[\203t\246\267\021\330#\271\313\002\022\025A\222\213\"#\260\220hn\021\331S\341b\2165\033\\2\226\317\030\300\204=">
```
Then i try to get human readable value;
```
String stringUtf8 = value.toStringUtf8();
```
```
A??????[?t???#??A??"#??hn?S?b?5\2????=
```

Then i check;
```
boolean validUtf8 = value.isValidUtf8();
```
```
false
```

How can i convert successfully ByteString to String in this situation? 
Or alternatively are there any other way to get transaction info about **sender address, receiver address, amount, type** etc. using trident?

**Comment by Ocea91** [comment]
you need to decode it, this would be helpful to you https://developers.tron.network/docs/parameter-encoding-and-decoding#parameter-decoding

**Comment by isaguler** [comment]
> you need to decode it, this would be helpful to you https://developers.tron.network/docs/parameter-encoding-and-decoding#parameter-decoding

when using "/wallet/gettransactionbyid" HTTP API via resttemplate etc. I can get human readable respone like;
```
{
  "ret": [
    {
      "contractRet": "SUCCESS"
    }
  ],
  "signature": [
    "33f003578d1d935465dcd9007bf0a39307bca69fc3cb2c50c33f9c325e4c7a1b7c7821ac51c92b79b5b4c17e0671c1d54599beb03594eccb9aacc8be3815fea701"
  ],
  "txID": "b4d76f7e875836737cb373043250d8912048bcfe0bc981d6462adbb2e0c46c7f",
  "raw_data": {
    "contract": [
      {
        "parameter": {
          "value": {
            "amount": 1000000,
            "owner_address": "TW7WayyhBi5rKbU2CT5UeY6tQ5udWCmypv",
            "to_address": "TPL4LDnw5aTtCtHFEBJEB89WvWCk6LTRrC"
          },
          "type_url": "type.googleapis.com/protocol.TransferContract"
        },
        "type": "TransferContract"
      }
    ],
    "ref_block_bytes": "589e",
    "ref_block_hash": "30c20010d1430ea7",
    "expiration": 1683639822000,
    "timestamp": 1683639761857
  },
  "raw_data_hex": "0a02589e220830c20010d1430ea740b0cd838680315a67080112630a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412320a1541dcf485c2e2b4bbd9e85b8374a6b711d823b9cb02121541928b2223b090686e11d953e1628e351b5c3296cf18c0843d70c1f7ff858031"
}
```
but I want to use trident library "org.tron.trident.core.getTransactionById" ( [https://developers.tron.network/reference/api-query-the-network#gettransactionbyid](https://developers.tron.network/reference/api-query-the-network#gettransactionbyid) ) . thats why I asked here to "convert ByteString value to human readable object". Your answwer leads to HTTP response and parsing abi encoded data. Am I wrong?

**Comment by Ocea91** [comment]
> > you need to decode it, this would be helpful to you https://developers.tron.network/docs/parameter-encoding-and-decoding#parameter-decoding
> 
> when using "/wallet/gettransactionbyid" HTTP API via resttemplate etc. I can get human readable respone like;
> 
> ```
> {
>   "ret": [
>     {
>       "contractRet": "SUCCESS"
>     }
>   ],
>   "signature": [
>     "33f003578d1d935465dcd9007bf0a39307bca69fc3cb2c50c33f9c325e4c7a1b7c7821ac51c92b79b5b4c17e0671c1d54599beb03594eccb9aacc8be3815fea701"
>   ],
>   "txID": "b4d76f7e875836737cb373043250d8912048bcfe0bc981d6462adbb2e0c46c7f",
>   "raw_data": {
>     "contract": [
>       {
>         "parameter": {
>           "value": {
>             "amount": 1000000,
>             "owner_address": "TW7WayyhBi5rKbU2CT5UeY6tQ5udWCmypv",
>             "to_address": "TPL4LDnw5aTtCtHFEBJEB89WvWCk6LTRrC"
>           },
>           "type_url": "type.googleapis.com/protocol.TransferContract"
>         },
>         "type": "TransferContract"
>       }
>     ],
>     "ref_block_bytes": "589e",
>     "ref_block_hash": "30c20010d1430ea7",
>     "expiration": 1683639822000,
>     "timestamp": 1683639761857
>   },
>   "raw_data_hex": "0a02589e220830c20010d1430ea740b0cd838680315a67080112630a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412320a1541dcf485c2e2b4bbd9e85b8374a6b711d823b9cb02121541928b2223b090686e11d953e1628e351b5c3296cf18c0843d70c1f7ff858031"
> }
> ```
> 
> but I want to use trident library "org.tron.trident.core.getTransactionById" ( https://developers.tron.network/reference/api-query-the-network#gettransactionbyid ) . thats why I asked here to "convert ByteString value to human readable object". Your answwer leads to HTTP response and parsing abi encoded data. Am I wrong?

At the very bottom of the page I pasted in the previous link, you will find the section of `decode the return value of a contract query operation`, you can try toHex that convert bytestring to hex first and then follow the section to crack the infos.

**Comment by isaguler** [comment]
I could not achieve to retrieve information for my case but thats my bad I guess. If there is no other way for this I think I am going to use HTTP API for get transaction info. Because this decoding process is requires more lines of coding and not so clear for integration to already complex app.

**Comment by Cletitia** [comment]
The exact 'thing' inside `parameter` is one of TRON's system contracts.
The transaction you were retriving is a TRX transfer, which coresponds to a [TransferContract](https://github.com/tronprotocol/java-tron/blob/develop/protocol/src/main/protos/core/contract/balance_contract.proto).
You will firstly unpack the parameter then you have the params easily. The demo is here.
```java
TransferContract result = transaction.getRawData().getContract(0).getParameter().unpack(TransferContract.class);
```

**Comment by isaguler** [comment]
> @isaguler, as I posted above, use the method toHexstring to convert bytestring to hex.

Thanks, with "**Numeric.toHexString()**" I can get hexAddress of Account. But I need public address (base58CheckAddress) of account for my case so I guess I can use "**Base58Check.bytesToBase58()**" method for this. 🙏

**Comment by Cletitia** [comment]
Usually we use the class of `org.bouncycastle.util.encoders.Hex` to achieve this.
```java
Hex.toHexString(result.getOwnerAddress().toByteArray()));
```
Trident has the function below for easy converting. The function is in `ApiWrapper`

```java
public static ByteString parseAddress(String address) {
        byte[] raw;
        if (address.startsWith("T")) {
            raw = Base58Check.base58ToBytes(address);
        } else if (address.startsWith("41")) {
            raw = Hex.decode(address);
        } else if (address.startsWith("0x")) {
            raw = Hex.decode(address.substring(2));
        } else {
            try {
                raw = Hex.decode(address);
            } catch (Exception e) {
                throw new IllegalArgumentException("Invalid address: " + address);
            }
        }
        return ByteString.copyFrom(raw);
    }
```
