### ISSUE TITLE
Provide support for gRPC interceptors in the ApiWrapper class

### ISSUE THREAD

**Issue by Aiden-777** [tronprotocol/trident#87]
Hello, I would like to request the addition of support for gRPC interceptors in the ApiWrapper class. Currently, there is no straightforward way to add interceptors to the gRPC channel used by the ApiWrapper. It would be beneficial to have a method, such as adding it to the constructor or providing a separate method to set the channel, that allows users to easily configure and utilize gRPC interceptors. This enhancement would enhance the flexibility and extensibility of the ApiWrapper class and enable developers to incorporate custom interceptors seamlessly. Thank you for considering this feature request.

```
public LimitApiWrapper(String grpcEndpoint, String grpcEndpointSolidity, String hexPrivateKey, ClientInterceptor clientInterceptor) {
    channel = ManagedChannelBuilder.forTarget(grpcEndpoint)
            .intercept(clientInterceptor)
            .usePlaintext().build();
    // ....
}
```

**Comment by xq-lu** [comment]
> 
Good idea.
gRPC interceptors can really help in many use cases, such as tracing, logging, and validating authentication tokens, and metrics when intercepting the request from the client or response from the server.
We will support it in the next release.
Thank you, anyway.

**Comment by Aiden-777** [comment]
Support in [0.7.0](https://github.com/tronprotocol/trident/releases/tag/0.7.0)
