### ISSUE TITLE
How to transfer TRON(TRX) specifically? Exact amount not getting transferred.

### ISSUE THREAD

**Issue by mamtamehra07** [tronprotocol/trident#88]
Hi,
I observe that the long amount value I specify for the transaction is not the exact TRX amount being received.
May I know in which coin the transaction is happening?
I want to **transfer 300 TRX.** Please help with this.

Below is the code I am using.

import lombok.extern.log4j.Log4j2;
import org.tron.trident.core.ApiWrapper;
import org.tron.trident.proto.Chain;
import org.tron.trident.proto.Response;
@Log4j2
public class TronTransaction {

    public static void main(String[] args) throws Exception {

        String fromAddress = "XXX";
        String toAddress = "XXXX";
        String PRIVATE_KEY = "XXXX";
        long amount = 300;
		
		ApiWrapper wrapper = ApiWrapper.ofShasta(PRIVATE_KEY);

//      Create transaction
        Response.TransactionExtention transaction = wrapper.transfer(fromAddress, toAddress, amount);

//        Sign with the binding private key
        Chain.Transaction signedTransaction = wrapper.signTransaction(transaction);

//      Broadcast
        String transactionHash = wrapper.broadcastTransaction(signedTransaction);

**Comment by Jake151987** [comment]
the unit of the amount is in sun, not TRX, for 300 TRX, it should be 300000000 as 1 TRX= 1000000.

**Comment by mamtamehra07** [comment]
Thank you so much.
