### ISSUE TITLE
Inconvenience caused by the changes in the getBlockByNum interface.

### ISSUE THREAD

**Issue by Aiden-777** [tronprotocol/trident#92]
In version 0.5.0, the modified BlockExtention does not include specific information about transactions, and the transaction count is always 0.

**Comment by xq-lu** [comment]
> 

hi, @Aiden-777 
I just run a test case of the getBlockByNum interface to test what you mentioned in this issue. the return transaction count is correct and not 0. and in version 0.5.0, the struct 'BlockExtention' contains the transaction infos represented by 'repeated TransactionExtention transactions = 1;'
Please make sure there are transactions truly in this block, you can check in 'https:nile.tronscan.org/#/blockchain/blocks'.
Also, below are the test codes I run locally, you may have a try.
`       ApiWrapper client = 
       ApiWrapper.ofNile("xxxxxxxxxx");
        BlockExtention block = client.getBlockByNum(37777084);
        System.out.println("tx amount => " + block.getTransactionsCount());
        System.out.println("tx amount => " + block.getTransactions(0));
`

**Comment by Aiden-777** [comment]
> > 
> 
> hi, @Aiden-777 I just run a test case of the getBlockByNum interface to test what you mentioned in this issue. the return transaction count is correct and not 0. and in version 0.5.0, the struct 'BlockExtention' contains the transaction infos represented by 'repeated TransactionExtention transactions = 1;' Please make sure there are transactions truly in this block, you can check in 'https:nile.tronscan.org/#/blockchain/blocks'. Also, below are the test codes I run locally, you may have a try. ` ApiWrapper client = ApiWrapper.ofNile("xxxxxxxxxx"); BlockExtention block = client.getBlockByNum(37777084); System.out.println("tx amount => " + block.getTransactionsCount()); System.out.println("tx amount => " + block.getTransactions(0));`

After conducting further testing, it was indeed found to contain transaction information. I sincerely apologize for the inconvenience and the time wasted.
