### ISSUE TITLE
use trident sdk api delegateResource by 2.0 on version 0.6.0 connect fullnode 4.7.2 will make a excption

### ISSUE THREAD

**Issue by 405560984** [tronprotocol/trident#95]
I use the trident SDK by version 0.6.0 and the node version is 4.7.2
now i use she SDK api delegateResource,
it will make an exception:
delegateResource fail ,param:from=TKqngb5tmJ5ArSBLos3azHV3wvGGtjmZKJ,recv=TGEsrHpBkjQH2iYdTsKdUkGGcbqpo8vLFU,amount=16118,resCode=1,error msg：createTransactionExtention error,UNIMPLEMENTED: Method not found: protocol.WalletSolidity/GetNowBlock2
org.tron.trident.core.exceptions.IllegalException: createTransactionExtention error,UNIMPLEMENTED: Method not found: protocol.WalletSolidity/GetNowBlock2
at org.tron.trident.core.ApiWrapper.createTransactionExtention(ApiWrapper.java:326)
at org.tron.trident.core.ApiWrapper.delegateResource(ApiWrapper.java:595)

i want to know how to fix this problem

as i read the code and it looks like at the function createTransaction at line 306, use blockingStubSolidity.getNowBlock2 has miss the function?

now my question is the function is miss by trident SDK or in fullnode ？

as i see the node computer, i open the RPC/HTTP port 50051 and HTTP prot 8081

so what next to do??

thanks!!!!!

**Comment by Jake151987** [comment]
@405560984 Please check if your solidity port for rpc is open and set to 50061.

**Comment by 405560984** [comment]
> @405560984 Please check if your solidity port for rpc is open and set to 50061.

now the question is the node is full not solidity, as i will change the SDK api???

now i have think is to del the code line 306 get the solidity function，because i can not change the node is full or solidity

or the solidity is a full???

**Comment by Bellgin** [comment]
@405560984 There is no solidity node now, just the Fullnode, containing all the functionality. No need to change the SDK API, just check your node config.conf file and see if the solidity port for RPC is 50061. If you want to use the solidity function, you have to make sure the solidity port is open.

**Comment by 405560984** [comment]
> @405560984 There is no solidity node now, just the Fullnode, containing all the functionality. No need to change the SDK API, just check your node config.conf file and see if the solidity port for RPC is 50061. If you want to use the solidity function, you have to make sure the solidity port is open.

OK, now i have see the node's config main_net_config.conf, the rpc port is 50051, the solidity prot 50061 is logged out, so as i will del the line 306
it seems work fine, because the node has no solidity function????

**Comment by Bellgin** [comment]
@405560984, as I mentioned above, the fullnode has all the solidity functions, you may modify the main_net_config.conf and make sure the solidity port is 50061. And then see if the method `blockingStubSolidity.getNowBlock2` works properly.

**Comment by 405560984** [comment]
> @405560984, as I mentioned above, the fullnode has all the solidity functions, you may modify the main_net_config.conf and make sure the solidity port is 50061. And then see if the method `blockingStubSolidity.getNowBlock2` works properly.

OK，i will try, thank you very much!!!
